version: '3.8'

volumes:
    pool_ruby_gems:

services:
  web:
    command: ./entrypoint.sh
    volumes:
      - .:/myapp
      - pool_ruby_gems:/var/tmp/pool_ruby_gems
      - /etc/ssl/private/${MY_URL}:/var/tmp/${MY_URL}
    ports:
      - "80:9292"
    build:
      context: .
    env_file:
      - .env
