version: '3.8'

volumes:
    pool_ruby_gems:

services:
  web:
    command: ./entrypoint.sh
    volumes:
      - .:/myapp
      - pool_ruby_gems:/var/tmp/pool_ruby_gems
      - $HOME/certificates/djalan.hopto.org:/var/tmp/djalan.hopto.org
    ports:
      - "443:3000"
    build:
      context: .
